### ISSUE TITLE
加多一个字典赋值的方法吧

### ISSUE THREAD

**Issue by harde1** [boyXiong/XWJsonToCode#3]
通过kvc就ok了，不要使用反射,太耗资源了，把字典里面的值，赋给相同名字的属性，这个是实用

**Comment by boyXiong** [comment]
KVC有时候会蹦的, MJExtension 字典转模型，效率还是不错的

**Comment by harde1** [comment]
动态对象吗，内存吃的怎么样？
会蹦做一个异常处理

**Comment by harde1** [comment]
说错了，应该是MJExtension 的CPU负载情况优化的怎么样？因为我在项目开发时候，使用runtime写了一些方便的方法，但是最后经常导致CPU负载过大，手机发热，尤其是这个数据model的，常使用runtime随意操纵赋值、插入新属性，结果都很坑

**Comment by harde1** [comment]
刚刚看了一下，MJExtension也是采取映射或者叫反射的方式进行动态赋值，而且也能递归赋值，跟我自己写的方式是一致的，我的库也可以做到同样的效果，但是可能优化程度没有它的高，可是我还是觉得它是避免不了CPU耗用的问题，如果大规模使用，例如每个接口的model都同样使用你的插件，生成了model，然后使用它来动态赋值，在高端的机器上面不明显，但是机子差点，15分钟后手机必定煮鸡蛋

**Comment by boyXiong** [comment]
你说的这个确实存在，如果这样的话，那你就自己写一个 通过字典转模型的代码，但是也就意味着，你有一个模型，就要写相关代码，实际上KVC就是通过runtime 来实现的，至于你说数据量非常大的时候，这个取决你们服务器怎么设计数据，如果嵌套层次一多自然会增加解析时间，如果你想减少CPU的消耗你可以面向字典开发

**Comment by harde1** [comment]
面向字典也很坑啊，字典不提供代码补全，就是编辑器效率高不起来，不过你说的也对，kvc也是runtime,可能内部实现也是跟反射有关，其实也吃了一定的资源，用工具查看的时候，的确多占了CPU，只不过它毕竟是有官方维护的，更加底层，优化也更好罢了

**Comment by boyXiong** [comment]
是的，数据的层次低，loop 就会少，就会好点
