### ISSUE TITLE
老失败

### ISSUE THREAD

**Issue by goodcyg** [boyXiong/XWJsonToCode#7]
你的想法不错。
但是我在xcode 7.2.1中测试，加入json后，生产的文件，说是当前目录下成功了，但是啥也没有，还是提示生成AppDelegate.h头文件？这个不合适吧？

**Comment by boyXiong** [comment]
用的是最新的不，为了防止 修改文件，我已经改成 没有侵入性的，生成代码了，另外，你的JSON 可以给我看看

**Comment by boyXiong** [comment]
另外生成 模型文件，需要你选中 一个文件类，也就是 新建的模型 类名是什么 如果你选中了 AppDelegate.h 这个文件，再使用的，那这个新的类，就对应这个名称
