### ISSUE TITLE
Can Add some prefix for log, such as: XWJsonToCode boyxiong:进来了

### ISSUE THREAD

**Issue by EdgarHz** [boyXiong/XWJsonToCode#8]
After I update my Xcode to 8.0 beta, I need to rebuild Alcatraz. Then there some log such as:
"boyxiong:进来了
boyxiong:进来了",
which made me frightened.

Can you add some prefix to the log. Your tool is useful, I need it.
Thank you very much.

**Comment by boyXiong** [comment]
Print log has been removed
